Repository uber-workflow/docker-control-buildkite-plugin, pull requests merged in 2020-02, with the labels that each got.

#1 Collapse log sections
  hooks/checkout
  hooks/command
  hooks/pre-exit
Labels: enhancement

#3 Copy artifacts folder
  LICENSE
  hooks/command
Labels: feature

#4 Ensure we remove the Docker image
  hooks/command
  hooks/pre-exit
Labels: feature

#6 Add artifacts download support
  README.md
  hooks/checkout
  hooks/command
  plugin.yml
Labels: docs
